# Generated by Django 3.0.5 on 2020-05-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addfilms', '0002_auto_20200505_1140'),
        ('addfilms', '0002_auto_20200505_1136'),
    ]

    operations = [
    ]
