# Generated by Django 3.0.5 on 2020-05-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addfilms', '0003_auto_20200520_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gener',
        ),
    ]
